apiVersion: v1
kind: PersistentVolume
metadata: 
  name: db-pv
spec:
  storageClassName: local-db-storage
  capacity: 
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user/db_backup"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec: 
  storageClassName: local-db-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      